# Generated by Django 4.2.3 on 2023-07-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_rename_categorias_categoria_rename_noticias_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, default='notidefault.png', null=True, upload_to='noticias'),
        ),
    ]
